# Generated by Django 4.2.7 on 2025-11-19 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(db_index=True, help_text='BCWS Station Code', max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('province', models.CharField(default='BC', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, help_text='Elevation in meters', max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fire Weather Station',
                'verbose_name_plural': 'Fire Weather Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HourlyObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateTimeField(db_index=True, help_text='Observation time')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in °C', max_digits=5, null=True)),
                ('relative_humidity', models.IntegerField(blank=True, help_text='Relative humidity in %', null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=2, help_text='Precipitation in mm', max_digits=6, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Wind speed in km/h', max_digits=5, null=True)),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('wind_gust', models.DecimalField(blank=True, decimal_places=2, help_text='Wind gust in km/h', max_digits=5, null=True)),
                ('hourly_ffmc', models.DecimalField(blank=True, decimal_places=3, help_text='Hourly Fine Fuel Moisture Code', max_digits=6, null=True)),
                ('hourly_isi', models.DecimalField(blank=True, decimal_places=3, help_text='Hourly Initial Spread Index', max_digits=6, null=True)),
                ('hourly_fwi', models.DecimalField(blank=True, decimal_places=3, help_text='Hourly Fire Weather Index', max_digits=6, null=True)),
                ('ffmc', models.DecimalField(blank=True, decimal_places=3, help_text='Fine Fuel Moisture Code', max_digits=6, null=True)),
                ('dmc', models.DecimalField(blank=True, decimal_places=3, help_text='Duff Moisture Code', max_digits=6, null=True)),
                ('dc', models.DecimalField(blank=True, decimal_places=3, help_text='Drought Code', max_digits=6, null=True)),
                ('isi', models.DecimalField(blank=True, decimal_places=3, help_text='Initial Spread Index', max_digits=6, null=True)),
                ('bui', models.DecimalField(blank=True, decimal_places=3, help_text='Buildup Index', max_digits=6, null=True)),
                ('fwi', models.DecimalField(blank=True, decimal_places=3, help_text='Fire Weather Index', max_digits=6, null=True)),
                ('danger_rating', models.CharField(blank=True, help_text='Fire danger rating (Low, Moderate, High, Very High, Extreme)', max_length=20, null=True)),
                ('snow_depth', models.DecimalField(blank=True, decimal_places=2, help_text='Snow depth in cm', max_digits=6, null=True)),
                ('solar_radiation', models.DecimalField(blank=True, decimal_places=2, help_text='Solar radiation', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='weather.weatherstation')),
            ],
            options={
                'verbose_name': 'Hourly Observation',
                'verbose_name_plural': 'Hourly Observations',
                'ordering': ['-observation_time'],
                'indexes': [models.Index(fields=['station', 'observation_time'], name='weather_hou_station_bdec0d_idx'), models.Index(fields=['observation_time'], name='weather_hou_observa_f4efd0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hourlyobservation',
            constraint=models.UniqueConstraint(fields=('station', 'observation_time'), name='unique_station_observation'),
        ),
    ]
