# Generated by Django 4.2.7 on 2025-11-18 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, help_text='ECCC Climate ID (7 digits)', max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('province', models.CharField(default='BC', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, help_text='Elevation in meters', max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather Station',
                'verbose_name_plural': 'Weather Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HourlyObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateTimeField(db_index=True, help_text='Observation time in UTC')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in °C', max_digits=5, null=True)),
                ('dew_point', models.DecimalField(blank=True, decimal_places=2, help_text='Dew point temperature in °C', max_digits=5, null=True)),
                ('relative_humidity', models.IntegerField(blank=True, help_text='Relative humidity in %', null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=2, help_text='Precipitation in mm', max_digits=6, null=True)),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in tens of degrees (0-36)', null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Wind speed in km/h', max_digits=5, null=True)),
                ('visibility', models.DecimalField(blank=True, decimal_places=2, help_text='Visibility in km', max_digits=6, null=True)),
                ('station_pressure', models.DecimalField(blank=True, decimal_places=2, help_text='Station pressure in kPa', max_digits=7, null=True)),
                ('humidex', models.DecimalField(blank=True, decimal_places=2, help_text='Humidex index', max_digits=5, null=True)),
                ('wind_chill', models.DecimalField(blank=True, decimal_places=2, help_text='Wind chill index', max_digits=5, null=True)),
                ('weather_description', models.TextField(blank=True, help_text='Weather conditions description', null=True)),
                ('data_quality', models.CharField(blank=True, help_text='Data quality flags', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='weather.weatherstation')),
            ],
            options={
                'verbose_name': 'Hourly Observation',
                'verbose_name_plural': 'Hourly Observations',
                'ordering': ['-observation_time'],
                'indexes': [models.Index(fields=['station', 'observation_time'], name='weather_hou_station_bdec0d_idx'), models.Index(fields=['observation_time'], name='weather_hou_observa_f4efd0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hourlyobservation',
            constraint=models.UniqueConstraint(fields=('station', 'observation_time'), name='unique_station_observation'),
        ),
    ]
