# Generated by Django 4.2.7 on 2025-11-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyobservation',
            name='snow_depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snow depth in cm', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='hourlyobservation',
            name='solar_radiation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solar radiation', max_digits=10, null=True),
        ),
    ]
